server:
  port: 9005
  servlet:
    context-path: /

spring:
  application:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;serverName=jjaco089.database.windows.net;databaseName=status-db;encrypt=true
    username: ${DBUSER}
    password: ${DBPASS}
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        includes:
          - "beans"
          - "health"
          - "info"
